name: quotes
description: Quotes, in an app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Serif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf

flutter_icons:
  image_path_android: "assets/images/icons/icon_android.png"
  image_path_ios: "assets/images/icons/icon_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/icons/icon_background.png"
  adaptive_icon_foreground: "assets/images/icons/icon_foreground.png"